LifeRPG/LifeRPG/urls.py
from django.conf.urls import url
from django.contrib import admin
from MemberApp import views as member_views
from VisitorApp import views as visitor_views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', visitor_views.home, name='home'),
    url(r'^contact', visitor_views.contact, name='contact'),
    url(r'^about',
        TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^register', visitor_views.register_view, name='register'),


    url(r'^login', auth_views.login,
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout', member_views.logout_view, name='logout'),
    url(r'^create_profile',
        member_views.create_profile, name='create_profile'),
    url(r'^tutorial', member_views.tutorial, name='tutorial'),
    url(r'^profile', member_views.profile, name='profile'),
    url(r'^levelup', member_views.levelup, name='levelup'),
    url(r'^missions', member_views.missions, name='missions'),
    url(r'^mission-review',
        member_views.mission_review, name='mission_review'),



    url(r'^admin/', admin.site.urls),
]

LifeRPG/MemberApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Mission(models.Model):
    image = models.CharField(max_length=200, null=True)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=200)
    science = models.CharField(max_length=200, null=True)


class Aspect(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=200, default='white')
    description = models.CharField(max_length=200, null=True)


class MissionAspect(models.Model):
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    aspect = models.ForeignKey(Aspect, on_delete=models.CASCADE)


class UserMissionRec(models.Model):
    rec_date = models.DateField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    rank = models.IntegerField()


class UserMissionRating(models.Model):
    log_time = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    rating = models.IntegerField()


class IntakeQuestion(models.Model):
    aspect = models.ForeignKey(Aspect, null=True, on_delete=models.SET_NULL)
    question = models.CharField(max_length=200)


class UserIntakeQuestion(models.Model):
    log_time = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(IntakeQuestion, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    @property
    def aspect(self):
        aspect = self.question.aspect
        return aspect


class Profile(models.Model):
    log_time = models.DateTimeField(default=datetime.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.IntegerField(default=0)
    level = models.IntegerField()
    xp = models.IntegerField()
    hearts = models.IntegerField()

    @property
    def user_aspects(self):
        user_aspects = UserAspect.objects.filter(user=self.user)
        return user_aspects

    @property
    def user_focus(self):
        user_focus = UserFocus.objects.filter(user=self.user,
                                              level=self.level)
        aspects = []
        for focus in user_focus:
            aspect = focus.aspect
            aspects.append(aspect)
        return aspects


class UserAspect(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    aspect = models.ForeignKey(Aspect, on_delete=models.CASCADE)
    points = models.IntegerField()


class UserFocus(models.Model):
    log_time = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    level = models.IntegerField()
    aspect = models.ForeignKey(Aspect, null=True, on_delete=models.SET_NULL)
    slot = models.IntegerField()

LifeRPG/templates/components/.#mission_card.html
Home@MacBook-Pro-2.local.24672

LifeRPG/templates/components/focus.html
<div class="row">
    <div class="col m10 offset-m1 s12 grey lighten-4">
        <span>Level Focus</span>
        <div class="row">
            {% for focus in profile.user_focus  %}
            <div class="col m4 s12 ">
                <div class="card {{focus.color}}">
                    <div class="card-content">
                        <span class="card-title">{{focus.name}}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

LifeRPG/templates/components/hearts.html
{% load static %}
{% for i in heart_range %}
<img src="{% static 'img/heart.svg' %}" style="height:50px; width:50px">
{% endfor %}
{% for i in empty_range %}
<img src="{% static 'img/empty_heart.svg' %}" style="height:50px; width:50px">
{% endfor %}

LifeRPG/templates/components/help_box.html
<div class="card horizontal amber lighten-5">
    <div class="card-image white">
        {% load static %}
        <img src="{% static 'img/wizard.svg' %}" style='width:100px; min-width:100px' >
    </div>
    <div class="card-content">
    <span class="card-title">{{ title }}</span>
        <p>{{ content }}</p>
    </div>
</div>

LifeRPG/templates/components/level_bar.html
<h5>
    <div class="left" style="margin-bottom:10px">{{ user.get_username }}</div>
    <div class="right">level {{ profile.level }}</div>
</h5>
<div class="progress purple lighten-4" style="height:8px">
    <div class="determinate purple" style="width: {{ profile.xp }}%"></div>
</div>
<p class="right" style="margin-top:-12px">{{ profile.xp }}/100 XP</p>
<br>

LifeRPG/templates/components/levelup_form.html
<div class="row">
    {% for field in form %}
    {% for error in field.errors %}
    <p class="red-text">{{ error }}</p>
    {% endfor %}
    {% endfor %}


    <div class="col m10 offset-m1 s12 grey lighten-4">
        <span>Level Focus</span>
        <div class="row">
            <div class="col m4  s12 ">
                <div class="card" id="slot1_card">
                    <div class="card-content">
                        <span class="card-title">slot1</span>
                    </div>
                </div>
            </div>
            <div class="col m4  s12">
                <div class="card" id="slot2_card"">
                    <div class="card-content">
                        <span class="card-title">slot2</span>
                    </div>
                </div>
            </div>
            <div class="col m4  s12">
                <div class="card" id="slot3_card">
                    <div class="card-content">
                        <span class="card-title">slot3</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    {% for user_aspect in profile.user_aspects %}
    <div class="col s12 m4">
        <div class="card {{user_aspect.aspect.color}} clickable">
            <div class="card-content">
                <span class="card-title">{{user_aspect.aspect.name}}</span>
                <p>{{user_aspect.aspect.description}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br>
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    {{field.as_hidden }}
    {% endfor %}
    <br>
    <div class="center">
        <a id="clear-button" class="btn-large waves-effect waves-light purple">
            Clear
        </a>
        <button type="submit" class="btn-large waves-effect waves-light purple center">
            Complete
        </button>
    </div>
</form>



<script>
 $( document ).ready(function() {
     var i = 0;
     $('.clickable').click(function() {
         i += 1;
         $('.clickable').removeClass("darken-2");
         var color = $(this).attr('class').split(' ')[1];
         //darken for click
         $(this).addClass("darken-2");

         var title = $(this).find('.card-title').text();

         $('#slot'+i+'_card').removeClass();
         $('#slot'+i+'_card').addClass('card');
         $('#slot'+i+'_card').find(".card-title").text(title);
         $('#slot'+i+'_card').addClass(color);
         $('#id_slot'+i).val(title);
     });
     $('#clear-button').click(function() {
         i = 0;
         for( var j=1; j<=3; j++){
             $('#slot'+j+'_card').find(".card-title").text('slot'+j);
             $('#slot'+j+'_card').removeClass();
             $('#slot'+j+'_card').addClass('card');
             $('#id_slot'+j).val('');
         }
     });
 });
</script>

LifeRPG/templates/components/stats.html
<div class="row">
    <div class="col s12 m10  offset-m1 card grey lighten-4" >
        Stats
        <table class="bordered" >
            <thead>
                <tr>
                    <th> </th>
                    <th> Aspect </th>
                    <th> Points </th>
                </tr>
            </thead>
            <tbody>
                {% for user_aspect in profile.user_aspects %}
                <tr>
                    <td class='{{user_aspect.aspect.color}}'> </td>
                    <td><h5>{{user_aspect.aspect.name}}</h5></td>
                    <td><h5>{{user_aspect.points}}</h5></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>